import Head from 'next/head'
import styles from "../styles/Home.module.css"


export default function Home({posts,users}) {
  const number=5
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1 className='title'>INDEX</h1>
       <style jsx>
        {
          `
          .title{
            background:${number>2? 'blue' :'red'}
          }
          `
        }
       </style>
       {posts?.map((user)=>(<div>
        {user.id}
       </div>))}
       {users?.map((user)=>(<div>
        {user.id}
       </div>))}
      </main>
    </>
  )
}
/*
export const getServerSideProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const posts = await res.json();
  return {
    props:{
      posts
    }
  }
}
*/

export const getStaticProps=async()=>{
  const res = await fetch('https://jsonplaceholder.typicode.com/users')
  const users = await res.json()

  return {
    props:{
      users
    }
  }
}