import Head from 'next/head'
import styles from "../styles/Home.module.css"


export default function Home() {
  const number=5
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1 className='title'>INDEX</h1>
       <style jsx>
        {
          `
          .title{
            background:${number>2? 'blue' :'red'}
          }
          `
        }
       </style>
      </main>
    </>
  )
}
